version: '3'
services:
  auth:
    build: ./packages/auth/
    container_name: 'epidraw-auth-test'
    command: bash -c 'yarn install && yarn test'
    depends_on:
      - database
    links:
      - database
    ports:
      - '8081:8081'
    volumes:
      - ./packages/auth/src:/usr/app/src/src
      - ./packages/auth/package.json:/usr/app/src/package.json
      - ./packages/auth/tsconfig.json:/usr/app/src/tsconfig.json
      - ./packages/auth/node_modules:/usr/app/src/node_modules
      - ./packages/auth/test:/usr/app/src/test
      - ./packages/shared:/usr/app/shared
  database:
    image: mongo
    container_name: 'epidraw-db'
    ports:
      - '27017-27019:27017-27019'
    logging:
      driver: none
