# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo

    steps:
      - checkout

      # run tests!
      - run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
