# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  auth:
    docker:
      - image: circleci/node:12.13.1
      - image: mongo
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: npm update
      - run: npm install
      - run: npm run auth.update
      - run: npm run auth.ci
      - run: npm run auth.test
  user:
    docker:
      - image: circleci/python:lastest
      - image: mongo
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: npm update
      - run: npm install
      - run: npm run auth.update
      - run: npm run auth.ci
      - run: npm run auth.test
workflows:
  version: 2
  microservies: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - auth
