# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  auth:
    docker:
      - image: circleci/node:12.13.1
      - image: mongo
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: npm update
      - run: npm install
      - run: npm run auth.update
      - run: npm run auth.ci
      - run: npm run auth.test
  user:
    docker:
      - image: circleci/python:latest
      - image: mongo
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run: npm update
      - run: npm install
      - run: npm run user.install
      - run: npm run user.test
workflows:
  version: 2
  microservies: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - user
      - auth
