version: '3'

services:
  auth:
    build:
      context: ../
      dockerfile: ./auth/Dockerfile.dev
    container_name: 'epidraw-auth-dev'
    depends_on:
      - database
    links:
      - database
    ports:
      - '8081:8081'
    volumes:
      - ./src:/epidraw/packages/auth/src
      - ../shared/lib:/epidraw/packages/shared/lib

  database:
    image: mongo
    container_name: 'epidraw-db'
    ports:
      - '27017-27019:27017-27019'
