version: '3'

services:
  auth:
    image: 'auth-test'
    build:
      context: ../
      dockerfile: ./auth/Dockerfile.test
    container_name: 'epidraw-auth-test'
    environment:
      - DATABASE_HOST=database
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./src:/epidraw/packages/auth/src
      - ./test:/epidraw/packages/auth/test
      - ./test/fixtures:/epidraw/packages/auth/test/fixtures
      - ../shared/lib:/epidraw/packages/shared/lib

  database:
    image: mongo
    container_name: 'epidraw-db-test'
    ports:
      - '27017-27019:27017-27019'
    logging:
      driver: none
