version: '3'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'epidraw-user-dev'
    depends_on:
      - database
    links:
      - database
    ports:
      - '5000:5000'
    volumes:
      - ./app.py:/epidraw/packages/user/app.py
      - ./src:/epidraw/packages/user/src

  database:
    image: mongo
    container_name: 'epidraw-user-db'
    ports:
      - '5001:27017'
